AI Programming

In [2]:
import numpy as np
np.__version__


'1.26.1'

# Exercise 1: Creating and Manipulating NumPy Arrays


* Create a 1D NumPy array from the list [5, 10, 15, 20, 25]. Convert the array to type float64 and print it.

In [3]:
l = [5, 10, 15, 20, 25]

v = np.array(l, dtype=np.float64)

v

array([ 5., 10., 15., 20., 25.])


* Create a 2D NumPy array from the nested list [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Print the shape and size of the array.

In [4]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

v = np.array(l, dtype=np.float64)

print("shape : " , v.shape, "\nlen : ", v.size)


shape :  (3, 3) 
len :  9


* Create a 3D NumPy array with random values of shape (2, 3, 4). Print the number of dimensions and the shape of the array.

In [5]:
l = np.random.randn(2 * 3 * 4)

print("N dimensions : ", l.ndim, ", shape : ", l.shape)

N dimensions :  1 , shape :  (24,)


# Exercise 3: Advanced Array Manipulations

* Create a 1D NumPy array with the numbers from 0 to 9. Reverse the array and print it.

In [6]:
l = np.arange(0, 10)
v = np.flip(l)

v

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

* Create a 2D NumPy array with the numbers from 0 to 11, arranged in a 3x4 shape. Extract a subarray consisting of the first two rows and the last two columns, and print it.

In [7]:
l = np.arange(0, 12).reshape(3,4)
rows, col = l.shape
# print(l)

new_l = l[0:2] 
new_l[:, [rows-1, rows]]

array([[2, 3],
       [6, 7]])

* Create a 2D NumPy array of shape (5, 5) with random integers between 0 and 10. Replace all elements greater than 5 with 0 and print the modified array.

In [8]:
l =  np.random.randint(0, 11, size=(5,5))

l[l > 5] = 0

l

array([[4, 3, 0, 4, 4],
       [0, 0, 0, 0, 4],
       [0, 3, 5, 0, 0],
       [2, 3, 0, 5, 4],
       [0, 0, 0, 1, 0]])

# Exercise 4: Array Initialization and Attributes
* Create a 3x3 identity matrix using NumPy and print its attributes: ndim, shape, size, itemsize, and nbytes.

In [9]:
i = np.identity(3)

print("n dimensions :", i.ndim, "\nshape: ", i.shape, "\nitemsize : ", i.itemsize, "\nn bytes : ", i.nbytes)

n dimensions : 2 
shape:  (3, 3) 
itemsize :  8 
n bytes :  72


* Create an array of 10 evenly spaced numbers between 0 and 5 using numpy.linspace(). Print the array and its datatype.

In [10]:
l = np.linspace( 0, 5, 10)

print("array :\n", l)
print("datatype : ", l.dtype)

array :
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
datatype :  float64


* Create a 3D array of shape (2, 3, 4) with random values from a standard normal distribution. Print the array and the sum of all elements.


In [11]:
l = np.random.randn(2, 3, 4)

print("array :\n", l)

l_sum = np.sum(l)
print("Sum of all elements:", l_sum)

array :
 [[[-0.99571929 -0.86083863 -0.26244437  0.23796071]
  [-0.54704068 -0.52617981  0.6701578  -0.87754796]
  [ 0.6827339  -0.33024673  0.4068885   0.35347918]]

 [[-1.526223    0.03659919  0.68503434  1.27110299]
  [-0.10173562  1.67385709 -0.44425605 -0.89295768]
  [ 0.74824966  0.93722739 -0.01809635  1.24561899]]]
Sum of all elements: 1.565623579637081


# Exercise 5: Fancy Indexing and Masking
* Create a 1D NumPy array with random integers between 0 and 50 of size 20. Use fancy indexing to extract elements at indices [2, 5, 7, 10, 15] and print them.

In [12]:
l = np.random.randint(0, 50, size=20)

indices = [2, 5, 7, 10, 15]

print("Extracted elements: ", l[indices])

Extracted elements:  [46  7 43 13 16]


* Create a 2D NumPy array with random integers between 0 and 30 of shape (4, 5). Use a boolean mask to select all elements greater than 15 and print them.


In [13]:
l = np.random.randint(0, 30, size=(4,5))

l[l > 15]

array([16, 27, 19, 21, 26, 17, 21])

* Create a 1D NumPy array of 10 random integers between -10 and 10. Use a boolean mask to set all negative values to zero and print the modified array.

In [14]:
l = np.random.randint(-10, 10, size=10)

l[l < 0] = 0

l

array([0, 0, 1, 0, 0, 1, 0, 0, 2, 5])

# Exercise 7: Combining and Splitting Arrays
* Create two 1D NumPy arrays of length 5 with random integers between 0 and 10. Concatenate the two arrays and print the result.

In [15]:
la = np.random.randint(0, 5, size=5)
lb= np.random.randint(0, 5, size=5)

new_l = np.concatenate((la, lb))

new_l

array([3, 4, 0, 2, 0, 4, 1, 2, 0, 2])

* Create a 2D NumPy array of shape (6, 4) with random integers between 0 and 10. Split the array into two equal parts along the row axis and print them.

In [16]:
l = np.random.randint(0, 10, size=(6,4))

np.split(l, 2, axis=0)

[array([[2, 4, 4, 6],
        [5, 5, 1, 6],
        [7, 6, 7, 9]]),
 array([[4, 6, 5, 6],
        [9, 1, 3, 1],
        [0, 2, 2, 9]])]

* Create a 2D NumPy array of shape (3, 6) with random integers between 0 and 10. Split the array into three equal parts along the column axis and print them.

In [17]:
l = np.random.randint(0, 10, size=(3,6))

np.hsplit(l, 3)

[array([[4, 6],
        [6, 1],
        [6, 4]]),
 array([[7, 2],
        [8, 1],
        [1, 5]]),
 array([[2, 6],
        [1, 4],
        [6, 6]])]

# Exercise 8: Mathematical Functions and Aggregations
* Create a 1D NumPy array with random integers between 1 and 100 of size 15. Compute and print the mean, median, standard deviation, and variance of the array.

In [18]:
l = np.random.randint(1, 100, size=15)

mean = np.mean(l)
median = np.median(l)
std_dev = np.std(l)
variance = np.var(l)

print("array :\n", l)
print("mean:", mean)
print("median:", median)
print("standard deviation:", std_dev)
print("variance:", variance)

array :
 [ 4 49  8 75 67 56 99 59 44 68 30 12  3 45  4]
mean: 41.53333333333333
median: 45.0
standard deviation: 29.202435210478974
variance: 852.7822222222222


* Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 50. Compute and print the sum of each row and each column.

In [19]:
l = np.random.randint(1, 50, size=(4,4))

sum_row = np.sum(l, axis=1)

sum_col = np.sum(l, axis=0)
print("sum row ", sum_row)
print("sum col ", sum_col)


sum row  [ 84  61 108  91]
sum col  [ 87  90 103  64]


* Create a 3D NumPy array of shape (2, 3, 4) with random integers between 1 and 20. Find the maximum and minimum values along each axis and print them.

In [20]:
l = np.random.randint(1, 21, size=(2, 3, 4))

for x in l:
    print(x)

print("axe 0 min : ", np.min(l, axis = 0))


[[ 5 12 12 12]
 [14 11 12  6]
 [13 15 11 13]]
[[ 5  8  7 11]
 [ 1 12 19  3]
 [ 9 10 12  2]]
axe 0 min :  [[ 5  8  7 11]
 [ 1 11 12  3]
 [ 9 10 11  2]]


# Exercise 9: Reshaping and Transposing Arrays
* Create a 1D NumPy array with the numbers from 1 to 12. Reshape the array to a 2D array of shape (3, 4) and print it.

In [21]:
l = np.arange(1,13)
l = l.reshape((3,4))
l


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

* Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Transpose the array and print the transposed array.

In [22]:
l = np.random.randint(1, 11, size=(3,4))

print(np.transpose(l))

[[ 5  2 10]
 [ 2  4  2]
 [ 3  3  7]
 [ 1  5  6]]


* Create a 2D NumPy array of shape (2, 3) with random integers between 1 and 10. Flatten the array to 1D and print the result.

In [23]:
l = np.random.randint(1, 11, size=(2,3))

print(l.flatten())


[ 5  4  7  1  2 10]


# Exercise 10: Broadcasting and Vectorized Operations
* Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Subtract the mean of each column from the respective column elements and print the result.

In [24]:
l = np.random.randint(1, 11, size=(3,4))

column_means = np.mean(l, axis=0)

r = l - column_means
print(r)


[[ 2.         -4.33333333 -0.66666667 -0.66666667]
 [-4.          2.66666667 -2.66666667 -0.66666667]
 [ 2.          1.66666667  3.33333333  1.33333333]]


* Create two 1D NumPy arrays of length 4 with random integers between 1 and 5. Use broadcasting to compute and print the outer product of the two arrays.

In [25]:
l = np.random.randint(1, 6, size=4)
l2 = np.random.randint(1, 6, size=4)


print("Array 1:", l)
print("Array 2:", l2)
np.outer(l, l2)

Array 1: [5 1 5 3]
Array 2: [2 3 2 3]


array([[10, 15, 10, 15],
       [ 2,  3,  2,  3],
       [10, 15, 10, 15],
       [ 6,  9,  6,  9]])

* Create a 2D NumPy array of shape (4, 5) with random integers between 1 and 10. Add 10 to all elements of the array that are greater than 5 and print the modified array.

In [26]:
l = np.random.randint(1,11,size=(4,5))
print(l)
l[l>5] = 10
print(l)


[[ 8  3  6  2 10]
 [ 7 10 10  4  5]
 [ 6  8  6  8  8]
 [10  4  4  9  9]]
[[10  3 10  2 10]
 [10 10 10  4  5]
 [10 10 10 10 10]
 [10  4  4 10 10]]


# Exercise 11: Sorting and Searching Arrays
* Create a 1D NumPy array with random integers between 1 and 20 of size 10. Sort the array in ascending order and print the sorted array.

In [27]:
l = np.random.randint(1,11,size=10)

print(l)

print(np.sort(l))

[4 9 6 3 2 6 3 1 5 5]
[1 2 3 3 4 5 5 6 6 9]


* Create a 2D NumPy array of shape (3, 5) with random integers between 1 and 50. Sort the array by the second column and print the result.

In [28]:
l = np.random.randint(1, 51, size=(3,5))

print(l)
print(l[l[:, 1].argsort()])


[[45 38 27 13 16]
 [15 38 49 42 45]
 [35 10 45 21  4]]
[[35 10 45 21  4]
 [45 38 27 13 16]
 [15 38 49 42 45]]


* Create a 1D NumPy array with random integers between 1 and 100 of size 15. Find and print the indices of all elements greater than 50.

In [29]:
l = np.random.randint(1, 101, size=15)
print(l)
print(l[l > 50])

[90 37 18 32 85 74 52 95 60 54  6 79 34 67 34]
[90 85 74 52 95 60 54 79 67]


# Exercise 12: Linear Algebra with NumPy
* Create a 2D NumPy array of shape (2, 2) with random integers between 1 and 10. Compute and print the determinant of the array.

In [30]:
l = np.random.randint(1, 11, size=(2,2))

print(l)
print(np.linalg.det(l))


[[4 9]
 [9 3]]
-69.00000000000001


* Create a 2D NumPy array of shape (3, 3) with random integers between 1 and 5. Compute and print the eigenvalues and eigenvectors of the array.

In [31]:
l = np.random.randint(1, 6, size=(3, 3))
print(l)
eigenvalues, eigenvectors = np.linalg.eig(l)
print(eigenvalues)
print(eigenvectors)

[[2 3 3]
 [5 5 3]
 [1 4 3]]
[10.0490278+0.j         -0.0245139+1.22150758j -0.0245139-1.22150758j]
[[ 0.45855542+0.j          0.03985454-0.44023884j  0.03985454+0.44023884j]
 [ 0.74340686+0.j         -0.51323991+0.31331743j -0.51323991-0.31331743j]
 [ 0.48690159+0.j          0.66559625+0.j          0.66559625-0.j        ]]


* Create two 2D NumPy arrays of shape (2, 3) and (3, 2) with random integers between 1 and 10. Compute and print the matrix product of the two arrays.

In [32]:
l = np.random.randint(1, 10, size=(2,3))
l2 = np.random.randint(1, 10, size=(3,2))

print(l)
print(l2)

print("matrix product : ", np.matmul(l, l2))



[[1 4 8]
 [2 3 4]]
[[8 7]
 [1 5]
 [4 2]]
matrix product :  [[44 43]
 [35 37]]


# Exercise 13: Random Sampling and Distributions
* Create a 1D NumPy array of 10 random samples from a uniform distribution over [0, 1) and print the array.

In [33]:
l = np.random.uniform(0, 1, 10)

l

array([0.10637183, 0.34133849, 0.30994591, 0.65838418, 0.31891343,
       0.08305577, 0.86663386, 0.75415927, 0.50359507, 0.57587669])

* Create a 2D NumPy array of shape (3, 3) with random samples from a normal distribution with mean 0 and standard deviation 1. Print the array.

In [34]:
l = np.random.normal(0, 1, (3, 3))

l

array([[-0.31316488, -0.1599846 , -0.39200663],
       [ 0.06647927, -0.22291137,  0.52689701],
       [-0.30686485, -0.28810024,  0.83849854]])

* Create a 1D NumPy array of 20 random integers between 1 and 100. Compute and print the histogram of the array with 5 bins.

In [35]:
l = np.random.randint(1, 101, 20)

hist, bins = np.histogram(l, bins=5)

print(l)
print("Histogram:", hist)
print("Bin :", bins)

[31 39 31 93 59 19 82 30 42 19 87 78 98 37 45 76 76 37 70  8]
Histogram: [3 7 2 4 4]
Bin : [ 8. 26. 44. 62. 80. 98.]


# Exercise 14: Advanced Indexing and Selection
* Create a 2D NumPy array of shape (5, 5) with random integers between 1 and 20. Select and print the diagonal elements of the array.

In [36]:
l = np.random.randint(1, 21, (5, 5))

diag = np.diagonal(l)

print(l)
print("diag :", diag)

[[ 9  9  5 13 16]
 [ 9 18 18 11  4]
 [ 7 16  7 12  7]
 [ 7  3 11  3  8]
 [11 12  2 11 12]]
diag : [ 9 18  7  3 12]


* Create a 1D NumPy array of 10 random integers between 1 and 50. Use advanced indexing to select and print all elements that are prime numbers.

In [37]:
l = np.random.randint(1, 51, size=10)
print(l)

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

prime_numbers = l[np.vectorize(is_prime)(l)]
print("Prime numbers:", prime_numbers)

[41  2  6 28  5 18  4 15 15 21]
Prime numbers: [41  2  5]


* Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 10. Select and print all elements that are even numbers.



In [38]:
l = np.random.randint(1, 11, size=(4, 4))
print(l)

even = l[l % 2 == 0]
print("even :", even)

[[ 4  1  7  6]
 [ 5  7 10  1]
 [ 5  4  3  4]
 [ 9 10  5  3]]
even : [ 4  6 10  4  4 10]


# Exercise 15: Handling Missing Data
* Create a 1D NumPy array of length 10 with random integers between 1 and 10. Introduce np.nan at random positions and print the array.

In [39]:
l = np.random.randint(1, 11, size=10)
print(l)

nan_indices = np.random.choice(l.size, replace=False)
# l[nan_indices] = np.nan
print(nan_indices)

[4 3 7 5 5 1 6 8 5 3]
5


* Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Replace all elements that are less than 5 with np.nan and print the array.

In [40]:
l = np.random.randint(1, 11, size=(3, 4)).astype(float)  
print(l)

l[l < 5] = np.nan

print(l)

[[ 1.  1. 10.  1.]
 [ 8. 10.  4.  9.]
 [ 7.  8.  4.  4.]]
[[nan nan 10. nan]
 [ 8. 10. nan  9.]
 [ 7.  8. nan nan]]


* Create a 1D NumPy array of length 15 with random integers between 1 and 20. Identify and print the indices of all np.nan values in the array.

In [41]:
l = np.random.randint(1, 21, size=15).astype(float)  # Converting to float for np.nan

l[[3, 7, 10]] = np.nan

nan_indices = np.where(np.isnan(l))[0]

print("l:\n", l)
print("\nIndices of np.nan values:", nan_indices)

l:
 [ 4. 15.  3. nan 18. 18. 14. nan 12.  5. nan 16. 11.  8.  7.]

Indices of np.nan values: [ 3  7 10]


# Exercise 16: Performance Optimization with NumPy
* Create a large 1D NumPy array with 1 million random integers between 1 and 100. Compute the mean and standard deviation using NumPy functions and measure the time taken.

In [42]:
import time

l = np.random.randint(1, 101, size=1_000_000)

start = time.time()

mean = np.mean(l)
std_dev = np.std(l)

end = time.time()

print("mean:", mean)
print("standard deviation:", std_dev)
print("temps :", end - start, "seconds")

mean: 50.513145
standard deviation: 28.890826108108698
temps : 0.00942540168762207 seconds


* Create two large 2D NumPy arrays of shape (1000, 1000) with random integers between 1 and 10. Perform element-wise addition and measure the time taken.

In [43]:
l = np.random.randint(1, 11, size=(1000, 1000))
l2 = np.random.randint(1, 11, size=(1000, 1000))

start = time.time()

result = l + l2

end = time.time()

print("temp:", end - start, "seconds")

temp: 0.0010190010070800781 seconds


* Create a 3D NumPy array of shape (100, 100, 100) with random integers between 1 and 10. Compute the sum along each axis and measure the time taken.

In [44]:
l = np.random.randint(1, 11, size=(100, 100, 100))
print(l)
start = time.time()

sum_axis0 = np.sum(l, axis=0) 
sum_axis1 = np.sum(l, axis=1) 
sum_axis2 = np.sum(l, axis=2) 

end = time.time()

print("Sum axis 0:", sum_axis0.shape)
print("Sum axis 1:", sum_axis1.shape)
print("Sum axis 2:", sum_axis2.shape)
print("\ntemps:", end - start, "seconds")

[[[10  6  9 ...  8  5  3]
  [ 2 10  1 ...  9  4  2]
  [ 2  8  3 ...  5  7  9]
  ...
  [ 2  3  7 ...  6  2  2]
  [ 5  5  7 ...  7  4  3]
  [ 3  1  9 ...  2  7  9]]

 [[ 6  5  7 ...  1 10  4]
  [ 3 10  6 ...  8  7  6]
  [ 7 10  2 ...  9  3  7]
  ...
  [ 3  2 10 ... 10  2 10]
  [ 4 10  4 ...  8  1  1]
  [ 8  6  5 ...  6  4 10]]

 [[ 4 10  3 ...  4  3  2]
  [ 6  2  1 ... 10  6 10]
  [ 3  3  8 ...  3  9  9]
  ...
  [ 9  9 10 ...  1  7  3]
  [ 7  2  5 ...  1  2  7]
  [ 9  9  5 ...  7  6  7]]

 ...

 [[ 5  9  5 ...  8  8  1]
  [ 1  3  5 ...  2  4  8]
  [10 10  9 ...  4  6  3]
  ...
  [ 3  7  8 ...  5  7  9]
  [ 3  5  2 ...  3  2  3]
  [ 5  6  8 ...  5  5  1]]

 [[ 7  7  8 ...  6  1 10]
  [ 1  9  7 ...  9  1  6]
  [ 1  5  3 ... 10  7  6]
  ...
  [10  8  3 ...  8  2  3]
  [ 4  9  4 ...  5  7  4]
  [10  9 10 ...  3  2  9]]

 [[ 1  6  8 ...  7 10  8]
  [ 1  9  3 ...  3  3  2]
  [ 1  2  7 ...  1  3  1]
  ...
  [ 4  9  2 ...  7  4  7]
  [ 5  1  9 ...  4  1  4]
  [ 9  7  4 ...  2  2  6]]]
Sum axis 0

# Exercise 17: Cumulative and Aggregate Functions
* Create a 1D NumPy array with the numbers from 1 to 10. Compute and print the cumulative sum and cumulative product of the array.



In [45]:
l = np.arange(1, 11)

sum = np.cumsum(l)
product = np.cumprod(l)

print(l)
print("sum:", sum)
print("product:", product)

[ 1  2  3  4  5  6  7  8  9 10]
sum: [ 1  3  6 10 15 21 28 36 45 55]
product: [      1       2       6      24     120     720    5040   40320  362880
 3628800]


* Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 20. Compute and print the cumulative sum along the rows and the columns.



In [46]:
l = np.random.randint(1, 21, size=(4, 4))

rows = np.cumsum(l, axis=1)
col = np.cumsum(l, axis=0)

print(l)
print("\nrows:\n", rows)
print("\ncolumns:\n", col)

[[12  4 10 19]
 [15 18 11 16]
 [20 10 13  2]
 [20 12 10 17]]

rows:
 [[12 16 26 45]
 [15 33 44 60]
 [20 30 43 45]
 [20 32 42 59]]

columns:
 [[12  4 10 19]
 [27 22 21 35]
 [47 32 34 37]
 [67 44 44 54]]


* Create a 1D NumPy array with 10 random integers between 1 and 50. Compute and print the minimum, maximum, and sum of the array.



In [47]:
l = np.random.randint(1, 51, size=10)

min = np.min(l)
max = np.max(l)
sum = np.sum(l)

print("l:", l)
print("min :", min)
print("max:", max)
print("sum:", sum)

l: [34  3  2 12 31 49 17 16 10 38]
min : 2
max: 49
sum: 212


# Exercise 18: Working with Dates and Times
* Create an array of 10 dates starting from today with a daily frequency and print the array.



In [48]:
today = np.datetime64('today', 'D')
dates = today + np.arange(10) 

print("dates :\n", dates)

dates :
 ['2024-09-27' '2024-09-28' '2024-09-29' '2024-09-30' '2024-10-01'
 '2024-10-02' '2024-10-03' '2024-10-04' '2024-10-05' '2024-10-06']


* Create an array of 5 dates starting from January 1, 2022 with a monthly frequency and print the array.



In [49]:
start = np.datetime64('2022-01-01', 'M') 
dates = start + np.arange(5)  

print("dates :\n", dates)

dates :
 ['2022-01' '2022-02' '2022-03' '2022-04' '2022-05']


* Create a 1D array with 10 random timestamps in the year 2023. Convert the timestamps to NumPy datetime64 objects and print the result.



In [50]:
start = np.datetime64('2023-01-01T00:00')
end = np.datetime64('2024-01-01T00:00')

random = start + np.random.randint(0, (end - start).astype('timedelta64[s]').astype(int), 10)

print("Random timestamps in 2023 as datetime64 objects:\n", random)

Random timestamps in 2023 as datetime64 objects:
 ['2053-08-09T00:20' '2035-07-16T12:38' '2078-06-01T22:00'
 '2043-07-27T07:27' '2050-10-18T12:16' '2051-12-26T05:11'
 '2081-06-08T01:31' '2081-06-20T09:07' '2067-09-08T17:31'
 '2075-04-05T19:56']


# Exercise 19: Creating Arrays with Custom Data Types
* Create a 1D NumPy array of length 5 with custom data type to store integers and their corresponding binary representation as strings. Print the array.



In [51]:
custom_dtype = np.dtype([('number', np.int32), ('binary', 'U10')])

l = np.zeros(5, dtype=custom_dtype)

for i in range(5):
    number = i + 1  # You can use any numbers here
    l[i] = (number, bin(number)[2:])

print(l)

[(1, '1') (2, '10') (3, '11') (4, '100') (5, '101')]


* Create a 2D NumPy array of shape (3, 3) with a custom data type to store complex numbers. Initialize the array with some complex numbers and print the array.



In [52]:
complex = np.dtype('complex')

l = np.array([[1+2j, 3+4j, 5+6j],
            [7+8j, 9+10j, 11+12j],
            [13+14j, 15+16j, 17+18j]], dtype=complex)

print(l)

[[ 1. +2.j  3. +4.j  5. +6.j]
 [ 7. +8.j  9.+10.j 11.+12.j]
 [13.+14.j 15.+16.j 17.+18.j]]


* Create a structured array to store information about books with fields: title (string), author (string), and pages (integer). Add information for three books and print the structured array.

In [53]:
book_dtype = np.dtype([('titre', 'U100'), 
                       ('auteur', 'U100'),
                       ('pages', np.int32)])  

livre = np.zeros(3, dtype=book_dtype)

livre[0] = ('titre1', 'auteur1', 322)
livre[1] = ('titre2', 'auteur2', 433)
livre[2] = ('titre3', 'auteur3', 444)

# Print the structured array
print(livre)

[('titre1', 'auteur1', 322) ('titre2', 'auteur2', 433)
 ('titre3', 'auteur3', 444)]


210